version: 1.6.8

server:
    port: 8208
    servlet:
        context-path: /icenter
spring:
    mvc:
        throw-exception-if-no-handler-found: true
    flyway:
        enabled: true
        locations: classpath:/db/migration
        baseline-on-migrate: true
        flyway.baseline-version: 1
    main:
        allow-bean-definition-overriding: true
hibernate:
    connection.url: jdbc:mysql://localhost/ionoff?autoReconnect=true&characterEncoding=UTF-8
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    connection.driver_class: com.mysql.jdbc.Driver
    connection.username: ionoff
    connection.password: ?6hqkHk+*D*e+WdY
    show_sql: false;

service.notify.url: http://service.ionoff.net/inotify
service.mediadata.url: http://service.ionoff.net/imedia/api
service.release.site: http://service.ionoff.net/release/ionoff/
service.release.latest: http://service.ionoff.net/release/ionoff/latest.json

tomcat.update.pool: update/pool
tomcat.update.cron: update/cron
tomcat.update.latest: update/latest.json

broker.http.url: http://localhost:8118
broker.mqtt.user: ionoff
broker.mqtt.pass: I0n0FFNet
broker.mqtt.qos: 2
broker.mqtt.url: tcp://localhost:1883
broker.mqtt.topic.ionoffnet: IOnOffNet
broker.mqtt.topic.controller: Controller
broker.mqtt.topic.mediaplayer: MediaPlayer

logging:
    level:
        org.hibernate.engine: ERROR
