version: 1.6.8

server:
    port: 8208
    servlet:
        context-path: /icenter
spring:
    mvc:
        throw-exception-if-no-handler-found: true
    flyway:
        enabled: true
        locations: classpath:/db/migration
        baseline-on-migrate: true
        flyway.baseline-version: 1
    main:
        allow-bean-definition-overriding: true

    datasource:
        hikari:
            connectionTimeout: 30000
            idleTimeout: 30000
            maxLifetime: 2000000
            maximumPoolSize: 20
            minimumIdle: 5
            poolName: SpringBootJPAHikariCP
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://127.0.0.1:3306/ionoff?autoReconnect=true&characterEncoding=UTF-8
        username: ionoff
        password: i@n@ff
    jpa:
        properties:
            hibernate:
                format_sql: true
                show_sql: false
                enable_lazy_load_no_trans: true

service.notify.url: http://service.ionoff.net/inotify
service.mediadata.url: http://service.ionoff.net/imedia/api
service.release.site: http://service.ionoff.net/release/ionoff/
service.release.latest: http://service.ionoff.net/release/ionoff/latest.json

tomcat.update.pool: update/pool
tomcat.update.cron: update/cron
tomcat.update.latest: update/latest.json

broker.http.url: http://localhost:8118
broker.mqtt.user: ionoff
broker.mqtt.pass: I0n0FFNet
broker.mqtt.qos: 2
broker.mqtt.url: tcp://localhost:1883
broker.mqtt.topic.ionoffnet: IOnOffNet
broker.mqtt.topic.controller: Controller
broker.mqtt.topic.mediaplayer: MediaPlayer
