server:
    port: 8018
    servlet:
        context-path: /csnlink
spring:
    mvc.throw-exception-if-no-handler-found: true
    resources.add-mappings: false
    flyway:
        enabled: true
        locations: classpath:/db/migration
        baseline-on-migrate: true
        flyway.baseline-version: 1
    datasource:
        url: jdbc:mysql://localhost:3306/csnlink?autoReconnect=true&characterEncoding=UTF-8&useSSL=false
        username: ionoff
        password: ?6hqkHk+*D*e+WdY
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect