###
POST http://localhost:8008/webhook/csn-albums HTTP/1.1
Content-Type: application/json; charset=utf-8
Accept: application/json; charset=utf-8

[ {
  "link" : "https://chiasenhac.vn/nghe-album/nhin-vao-noi-nho-chang-oc-tuong-tu-xssmws73q894tw.html",
  "title" : null,
  "artists" : null,
  "releaseDate" : null
}, {
  "link" : "https://chiasenhac.vn/nghe-album/anh-van-doi-cho-xssmcb3mq8vqw8.html",
  "title" : null,
  "artists" : null,
  "releaseDate" : null
}, {
  "link" : "https://chiasenhac.vn/nghe-album/can-moi-tinh-con-dau-xssmqr6dq8eakm.html",
  "title" : null,
  "artists" : null,
  "releaseDate" : null
}, {
  "link" : "https://chiasenhac.vn/nghe-album/co-kiep-sau-khong-xssmqcswq8ev49.html",
  "title" : null,
  "artists" : null,
  "releaseDate" : null
}, {
  "link" : "https://chiasenhac.vn/nghe-album/ngoi-sao-bay-xssmt7rsq8fta4.html",
  "title" : null,
  "artists" : null,
  "releaseDate" : null
}, {
  "link" : "https://chiasenhac.vn/nghe-album/the-best-of-dan-truong-xsswzz5zq911h1.html",
  "title" : null,
  "artists" : null,
  "releaseDate" : null
}, {
  "link" : "https://chiasenhac.vn/nghe-album/mua-tren-cuoc-tinh-3-xsswzvz6q9121k.html",
  "title" : null,
  "artists" : null,
  "releaseDate" : null
} ]
