version: '3'

services:

  ionoff:
    environment:
      JAVA_OPTS: -DMEMCACHED_NODE_01=memcached:11211 -DMEMCACHED_NODE_02=memcached:11211 -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n
    image: ionoff:latest
    networks:
      app_net:
        ipv4_address: 172.19.1.88
    ports:
      - 8080:8080
    volumes:
      - ${HOME}/Projects/ionoff/ionoff.server/target/icenter.war:/usr/local/tomcat/webapps/icenter.war
      - ./ionoff.xml:/usr/local/tomcat/conf/Catalina/localhost/ionoff.xml
      - ${HOME}/Projects/ionoff/ionoff.client:/usr/local/tomcat/tmp/ionoff.client

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.1.0/24
      driver: default