version: '3'

services:

  ionoff:
    environment:
      JAVA_OPTS: -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n -Dspring.profiles.active=dev
    image: ionoff:latest
    networks:
      app_net:
        ipv4_address: 172.19.1.88
    ports:
      - 8208:8080
    volumes:
      - ${HOME}/Projects/ionoff/ionoff.server/target/icenter.war:/usr/local/tomcat/webapps/icenter.war

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.1.0/24
      driver: default