server.port: 8086
spring:
    flyway:
        enabled: true
        locations: "classpath:/db/migration"
        baseline-description: #
        baseline-on-migrate: true
        flyway.baseline-version: 1
    datasource:
        url: jdbc:mysql://localhost/webhook?autoReconnect=true&characterEncoding=UTF-8
        username: root
        password: ionoff$db
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect