server:
    port: 8008
    servlet:
        context-path: /webhook
spring:
    mvc.throw-exception-if-no-handler-found: true
    resources.add-mappings: false
    flyway:
        enabled: true
        locations: classpath:/db/migration
        baseline-on-migrate: true
        flyway.baseline-version: 1
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/webhook?autoReconnect=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect