version: '3'

services:

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5.7
    networks:
      app_net:
        ipv4_address: 192.19.1.7
    ports:
      - 3306:3306

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.19.1.0/24
      driver: default